approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
author_approval: ignored
reviewers:
  name: programmers
  required: 1
  members:
  - benhayesuni
  - darcysandall
  - fordkilleenuni
  
  name: designers
  required: 1
  members:
  - andrewspalato
  - chrisslive95
  - MisterWolfen
  - Scyfon
  - sparcellbrooke
  